version: "3.9"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      APP_ENV: development
      DB_HOST: db
      DB_NAME: cholestofit
      DB_USER: cholestofit
      DB_PASS: secret
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      OPENAI_BASE_URL: ${OPENAI_BASE_URL:-https://api.openai.com}
      OPENAI_MODEL: ${OPENAI_MODEL:-gpt-4o-mini}
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: cholestofit
      MYSQL_USER: cholestofit
      MYSQL_PASSWORD: secret
    ports:
      - "${MYSQL_HOST_PORT:-3307}:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
