CREATE TABLE IF NOT EXISTS pressure_readings (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  measured_at DATETIME NOT NULL,
  systolic INT NOT NULL,
  diastolic INT NOT NULL,
  pulse INT NOT NULL,
  advice TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
