ALTER TABLE lipids
  ADD COLUMN glucose DECIMAL(4,2) NULL AFTER trig,
  ADD COLUMN question TEXT NULL AFTER note,
  ADD COLUMN advice TEXT NULL AFTER question,
  ADD COLUMN created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP AFTER advice;
